services:
  - type: web
    name: wa-permit-tracker
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wa-permit-tracker-db
          property: connectionString
      - key: NODE_ENV
        value: production